// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: forex/v1/order.proto

package forexv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitOrderRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Side             *int32                 `protobuf:"varint,1,opt,name=side" json:"side,omitempty"`       // 1 = buy, 2 = sell
	Segment          *int32                 `protobuf:"varint,2,opt,name=segment" json:"segment,omitempty"` // 1 = Retail, 2 = Corporate, 3 = Treasury
	AllowPartialFill *bool                  `protobuf:"varint,3,opt,name=allow_partial_fill,json=allowPartialFill" json:"allow_partial_fill,omitempty"`
	ClientId         *string                `protobuf:"bytes,4,opt,name=client_id,json=clientId" json:"client_id,omitempty"`                            // client's unique identifier
	ClientInn        *string                `protobuf:"bytes,5,opt,name=client_inn,json=clientInn" json:"client_inn,omitempty"`                         // client's INN (taxpayer identification number)
	CurrencyPair     *string                `protobuf:"bytes,6,opt,name=currency_pair,json=currencyPair" json:"currency_pair,omitempty"`                // e.g. "USD/TJS"
	Quantity         *string                `protobuf:"bytes,7,opt,name=quantity" json:"quantity,omitempty"`                                            // quantity is in the Base currency (the first currency in the pair)
	LimitRate        *string                `protobuf:"bytes,8,opt,name=limit_rate,json=limitRate" json:"limit_rate,omitempty"`                         // client's rate, positive decimal string
	RefId            *string                `protobuf:"bytes,9,opt,name=ref_id,json=refId" json:"ref_id,omitempty"`                                     // partner's reference id, up to 128 chars, prevents duplicate orders on retry
	OrderDay         *string                `protobuf:"bytes,10,opt,name=order_day,json=orderDay" json:"order_day,omitempty"`                           // order day 'YYYY-MM-DD'
	MinTradeQuantity *string                `protobuf:"bytes,11,opt,name=min_trade_quantity,json=minTradeQuantity" json:"min_trade_quantity,omitempty"` // minimum trade quantity if allow_partial_fill is true, decimal string
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitOrderRequest) Reset() {
	*x = SubmitOrderRequest{}
	mi := &file_forex_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderRequest) ProtoMessage() {}

func (x *SubmitOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderRequest.ProtoReflect.Descriptor instead.
func (*SubmitOrderRequest) Descriptor() ([]byte, []int) {
	return file_forex_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitOrderRequest) GetSide() int32 {
	if x != nil && x.Side != nil {
		return *x.Side
	}
	return 0
}

func (x *SubmitOrderRequest) GetSegment() int32 {
	if x != nil && x.Segment != nil {
		return *x.Segment
	}
	return 0
}

func (x *SubmitOrderRequest) GetAllowPartialFill() bool {
	if x != nil && x.AllowPartialFill != nil {
		return *x.AllowPartialFill
	}
	return false
}

func (x *SubmitOrderRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *SubmitOrderRequest) GetClientInn() string {
	if x != nil && x.ClientInn != nil {
		return *x.ClientInn
	}
	return ""
}

func (x *SubmitOrderRequest) GetCurrencyPair() string {
	if x != nil && x.CurrencyPair != nil {
		return *x.CurrencyPair
	}
	return ""
}

func (x *SubmitOrderRequest) GetQuantity() string {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return ""
}

func (x *SubmitOrderRequest) GetLimitRate() string {
	if x != nil && x.LimitRate != nil {
		return *x.LimitRate
	}
	return ""
}

func (x *SubmitOrderRequest) GetRefId() string {
	if x != nil && x.RefId != nil {
		return *x.RefId
	}
	return ""
}

func (x *SubmitOrderRequest) GetOrderDay() string {
	if x != nil && x.OrderDay != nil {
		return *x.OrderDay
	}
	return ""
}

func (x *SubmitOrderRequest) GetMinTradeQuantity() string {
	if x != nil && x.MinTradeQuantity != nil {
		return *x.MinTradeQuantity
	}
	return ""
}

type SubmitOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *int64                 `protobuf:"varint,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	Status        *int32                 `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
	Cause         *string                `protobuf:"bytes,3,opt,name=cause" json:"cause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderResponse) Reset() {
	*x = SubmitOrderResponse{}
	mi := &file_forex_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderResponse) ProtoMessage() {}

func (x *SubmitOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderResponse.ProtoReflect.Descriptor instead.
func (*SubmitOrderResponse) Descriptor() ([]byte, []int) {
	return file_forex_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitOrderResponse) GetOrderId() int64 {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return 0
}

func (x *SubmitOrderResponse) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *SubmitOrderResponse) GetCause() string {
	if x != nil && x.Cause != nil {
		return *x.Cause
	}
	return ""
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      *string                `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	OrderId       *int64                 `protobuf:"varint,2,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	OrderDay      *string                `protobuf:"bytes,3,opt,name=order_day,json=orderDay" json:"order_day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_forex_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_forex_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *CancelOrderRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *CancelOrderRequest) GetOrderId() int64 {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return 0
}

func (x *CancelOrderRequest) GetOrderDay() string {
	if x != nil && x.OrderDay != nil {
		return *x.OrderDay
	}
	return ""
}

type CancelOrderResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           *bool                  `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	RemainingQuantity *string                `protobuf:"bytes,2,opt,name=remaining_quantity,json=remainingQuantity" json:"remaining_quantity,omitempty"` // remaining qty at cancellation, for fund release
	OrderStatus       *int32                 `protobuf:"varint,3,opt,name=order_status,json=orderStatus" json:"order_status,omitempty"`
	Cause             *string                `protobuf:"bytes,4,opt,name=cause" json:"cause,omitempty"`
	RefId             *string                `protobuf:"bytes,5,opt,name=ref_id,json=refId" json:"ref_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_forex_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_forex_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderResponse) GetSuccess() bool {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return false
}

func (x *CancelOrderResponse) GetRemainingQuantity() string {
	if x != nil && x.RemainingQuantity != nil {
		return *x.RemainingQuantity
	}
	return ""
}

func (x *CancelOrderResponse) GetOrderStatus() int32 {
	if x != nil && x.OrderStatus != nil {
		return *x.OrderStatus
	}
	return 0
}

func (x *CancelOrderResponse) GetCause() string {
	if x != nil && x.Cause != nil {
		return *x.Cause
	}
	return ""
}

func (x *CancelOrderResponse) GetRefId() string {
	if x != nil && x.RefId != nil {
		return *x.RefId
	}
	return ""
}

// required partner_id and client_id
type FilterClientOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *int64                 `protobuf:"varint,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	Side          *int32                 `protobuf:"varint,2,opt,name=side" json:"side,omitempty"`
	Status        *int32                 `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	Limit         *int32                 `protobuf:"varint,4,opt,name=limit" json:"limit,omitempty"` // max = 100
	Offset        *int32                 `protobuf:"varint,5,opt,name=offset" json:"offset,omitempty"`
	ClientId      *string                `protobuf:"bytes,6,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	CurrencyPair  *string                `protobuf:"bytes,7,opt,name=currency_pair,json=currencyPair" json:"currency_pair,omitempty"`
	OrderDayFrom  *string                `protobuf:"bytes,8,opt,name=order_day_from,json=orderDayFrom" json:"order_day_from,omitempty"` // 2026-04-01
	OrderDayTo    *string                `protobuf:"bytes,9,opt,name=order_day_to,json=orderDayTo" json:"order_day_to,omitempty"`       // 2026-04-01
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterClientOrdersRequest) Reset() {
	*x = FilterClientOrdersRequest{}
	mi := &file_forex_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterClientOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterClientOrdersRequest) ProtoMessage() {}

func (x *FilterClientOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterClientOrdersRequest.ProtoReflect.Descriptor instead.
func (*FilterClientOrdersRequest) Descriptor() ([]byte, []int) {
	return file_forex_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *FilterClientOrdersRequest) GetOrderId() int64 {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return 0
}

func (x *FilterClientOrdersRequest) GetSide() int32 {
	if x != nil && x.Side != nil {
		return *x.Side
	}
	return 0
}

func (x *FilterClientOrdersRequest) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *FilterClientOrdersRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *FilterClientOrdersRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *FilterClientOrdersRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *FilterClientOrdersRequest) GetCurrencyPair() string {
	if x != nil && x.CurrencyPair != nil {
		return *x.CurrencyPair
	}
	return ""
}

func (x *FilterClientOrdersRequest) GetOrderDayFrom() string {
	if x != nil && x.OrderDayFrom != nil {
		return *x.OrderDayFrom
	}
	return ""
}

func (x *FilterClientOrdersRequest) GetOrderDayTo() string {
	if x != nil && x.OrderDayTo != nil {
		return *x.OrderDayTo
	}
	return ""
}

type FilterClientOrdersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This is the list of all matching orders
	Orders        []*OrderInfo `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterClientOrdersResponse) Reset() {
	*x = FilterClientOrdersResponse{}
	mi := &file_forex_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterClientOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterClientOrdersResponse) ProtoMessage() {}

func (x *FilterClientOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterClientOrdersResponse.ProtoReflect.Descriptor instead.
func (*FilterClientOrdersResponse) Descriptor() ([]byte, []int) {
	return file_forex_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *FilterClientOrdersResponse) GetOrders() []*OrderInfo {
	if x != nil {
		return x.Orders
	}
	return nil
}

type OrderInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderId           *int64                 `protobuf:"varint,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	Side              *int32                 `protobuf:"varint,2,opt,name=side" json:"side,omitempty"`
	Segment           *int32                 `protobuf:"varint,3,opt,name=segment" json:"segment,omitempty"`
	Status            *int32                 `protobuf:"varint,4,opt,name=status" json:"status,omitempty"`
	AllowPartialFill  *bool                  `protobuf:"varint,5,opt,name=allow_partial_fill,json=allowPartialFill" json:"allow_partial_fill,omitempty"`
	CurrencyPair      *string                `protobuf:"bytes,6,opt,name=currency_pair,json=currencyPair" json:"currency_pair,omitempty"`
	Quantity          *string                `protobuf:"bytes,7,opt,name=quantity" json:"quantity,omitempty"`
	LimitRate         *string                `protobuf:"bytes,8,opt,name=limit_rate,json=limitRate" json:"limit_rate,omitempty"`
	RefId             *string                `protobuf:"bytes,9,opt,name=ref_id,json=refId" json:"ref_id,omitempty"`
	MinTradeQuantity  *string                `protobuf:"bytes,10,opt,name=min_trade_quantity,json=minTradeQuantity" json:"min_trade_quantity,omitempty"`
	RemainingQuantity *string                `protobuf:"bytes,11,opt,name=remaining_quantity,json=remainingQuantity" json:"remaining_quantity,omitempty"`
	CreatedAt         *string                `protobuf:"bytes,12,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	OrderDay          *string                `protobuf:"bytes,13,opt,name=order_day,json=orderDay" json:"order_day,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrderInfo) Reset() {
	*x = OrderInfo{}
	mi := &file_forex_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInfo) ProtoMessage() {}

func (x *OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInfo.ProtoReflect.Descriptor instead.
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return file_forex_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *OrderInfo) GetOrderId() int64 {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return 0
}

func (x *OrderInfo) GetSide() int32 {
	if x != nil && x.Side != nil {
		return *x.Side
	}
	return 0
}

func (x *OrderInfo) GetSegment() int32 {
	if x != nil && x.Segment != nil {
		return *x.Segment
	}
	return 0
}

func (x *OrderInfo) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *OrderInfo) GetAllowPartialFill() bool {
	if x != nil && x.AllowPartialFill != nil {
		return *x.AllowPartialFill
	}
	return false
}

func (x *OrderInfo) GetCurrencyPair() string {
	if x != nil && x.CurrencyPair != nil {
		return *x.CurrencyPair
	}
	return ""
}

func (x *OrderInfo) GetQuantity() string {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return ""
}

func (x *OrderInfo) GetLimitRate() string {
	if x != nil && x.LimitRate != nil {
		return *x.LimitRate
	}
	return ""
}

func (x *OrderInfo) GetRefId() string {
	if x != nil && x.RefId != nil {
		return *x.RefId
	}
	return ""
}

func (x *OrderInfo) GetMinTradeQuantity() string {
	if x != nil && x.MinTradeQuantity != nil {
		return *x.MinTradeQuantity
	}
	return ""
}

func (x *OrderInfo) GetRemainingQuantity() string {
	if x != nil && x.RemainingQuantity != nil {
		return *x.RemainingQuantity
	}
	return ""
}

func (x *OrderInfo) GetCreatedAt() string {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return ""
}

func (x *OrderInfo) GetOrderDay() string {
	if x != nil && x.OrderDay != nil {
		return *x.OrderDay
	}
	return ""
}

type GetOrderBookDepthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segment       *int32                 `protobuf:"varint,1,opt,name=segment" json:"segment,omitempty"`
	MaxLevels     *int32                 `protobuf:"varint,2,opt,name=max_levels,json=maxLevels" json:"max_levels,omitempty"` // optional; default 20, max 50
	ClientId      *string                `protobuf:"bytes,3,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	CurrencyPair  *string                `protobuf:"bytes,4,opt,name=currency_pair,json=currencyPair" json:"currency_pair,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookDepthRequest) Reset() {
	*x = GetOrderBookDepthRequest{}
	mi := &file_forex_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookDepthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookDepthRequest) ProtoMessage() {}

func (x *GetOrderBookDepthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookDepthRequest.ProtoReflect.Descriptor instead.
func (*GetOrderBookDepthRequest) Descriptor() ([]byte, []int) {
	return file_forex_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderBookDepthRequest) GetSegment() int32 {
	if x != nil && x.Segment != nil {
		return *x.Segment
	}
	return 0
}

func (x *GetOrderBookDepthRequest) GetMaxLevels() int32 {
	if x != nil && x.MaxLevels != nil {
		return *x.MaxLevels
	}
	return 0
}

func (x *GetOrderBookDepthRequest) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *GetOrderBookDepthRequest) GetCurrencyPair() string {
	if x != nil && x.CurrencyPair != nil {
		return *x.CurrencyPair
	}
	return ""
}

type GetOrderBookDepthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bids          []*PriceLevel          `protobuf:"bytes,1,rep,name=bids" json:"bids,omitempty"` // buy side, descending by rate (best bid first)
	Asks          []*PriceLevel          `protobuf:"bytes,2,rep,name=asks" json:"asks,omitempty"` // sell side, ascending by rate (best ask first)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookDepthResponse) Reset() {
	*x = GetOrderBookDepthResponse{}
	mi := &file_forex_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookDepthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookDepthResponse) ProtoMessage() {}

func (x *GetOrderBookDepthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookDepthResponse.ProtoReflect.Descriptor instead.
func (*GetOrderBookDepthResponse) Descriptor() ([]byte, []int) {
	return file_forex_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderBookDepthResponse) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *GetOrderBookDepthResponse) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

type PriceLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          *string                `protobuf:"bytes,1,opt,name=rate" json:"rate,omitempty"`                                        // limit rate at this level
	TotalQuantity *string                `protobuf:"bytes,2,opt,name=total_quantity,json=totalQuantity" json:"total_quantity,omitempty"` // aggregated available quantity across all orders at this rate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	mi := &file_forex_v1_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_forex_v1_order_proto_rawDescGZIP(), []int{9}
}

func (x *PriceLevel) GetRate() string {
	if x != nil && x.Rate != nil {
		return *x.Rate
	}
	return ""
}

func (x *PriceLevel) GetTotalQuantity() string {
	if x != nil && x.TotalQuantity != nil {
		return *x.TotalQuantity
	}
	return ""
}

type SubscribeOrderEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeOrderEventsRequest) Reset() {
	*x = SubscribeOrderEventsRequest{}
	mi := &file_forex_v1_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeOrderEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOrderEventsRequest) ProtoMessage() {}

func (x *SubscribeOrderEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOrderEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeOrderEventsRequest) Descriptor() ([]byte, []int) {
	return file_forex_v1_order_proto_rawDescGZIP(), []int{10}
}

type SubscribeOrderEventsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderId           *int64                 `protobuf:"varint,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	EventType         *int32                 `protobuf:"varint,2,opt,name=event_type,json=eventType" json:"event_type,omitempty"` // order status
	EventTimestamp    *string                `protobuf:"bytes,3,opt,name=event_timestamp,json=eventTimestamp" json:"event_timestamp,omitempty"`
	RemainingQuantity *string                `protobuf:"bytes,4,opt,name=remaining_quantity,json=remainingQuantity" json:"remaining_quantity,omitempty"`
	RefId             *string                `protobuf:"bytes,5,opt,name=ref_id,json=refId" json:"ref_id,omitempty"`
	OrderDay          *string                `protobuf:"bytes,6,opt,name=order_day,json=orderDay" json:"order_day,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubscribeOrderEventsResponse) Reset() {
	*x = SubscribeOrderEventsResponse{}
	mi := &file_forex_v1_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeOrderEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOrderEventsResponse) ProtoMessage() {}

func (x *SubscribeOrderEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOrderEventsResponse.ProtoReflect.Descriptor instead.
func (*SubscribeOrderEventsResponse) Descriptor() ([]byte, []int) {
	return file_forex_v1_order_proto_rawDescGZIP(), []int{11}
}

func (x *SubscribeOrderEventsResponse) GetOrderId() int64 {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return 0
}

func (x *SubscribeOrderEventsResponse) GetEventType() int32 {
	if x != nil && x.EventType != nil {
		return *x.EventType
	}
	return 0
}

func (x *SubscribeOrderEventsResponse) GetEventTimestamp() string {
	if x != nil && x.EventTimestamp != nil {
		return *x.EventTimestamp
	}
	return ""
}

func (x *SubscribeOrderEventsResponse) GetRemainingQuantity() string {
	if x != nil && x.RemainingQuantity != nil {
		return *x.RemainingQuantity
	}
	return ""
}

func (x *SubscribeOrderEventsResponse) GetRefId() string {
	if x != nil && x.RefId != nil {
		return *x.RefId
	}
	return ""
}

func (x *SubscribeOrderEventsResponse) GetOrderDay() string {
	if x != nil && x.OrderDay != nil {
		return *x.OrderDay
	}
	return ""
}

var File_forex_v1_order_proto protoreflect.FileDescriptor

const file_forex_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x14forex/v1/order.proto\x12\bforex.v1\"\xee\x02\n" +
	"\x12SubmitOrderRequest\x12\x12\n" +
	"\x04side\x18\x01 \x01(\x05R\x04side\x12\x18\n" +
	"\asegment\x18\x02 \x01(\x05R\asegment\x12,\n" +
	"\x12allow_partial_fill\x18\x03 \x01(\bR\x10allowPartialFill\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"client_inn\x18\x05 \x01(\tR\tclientInn\x12#\n" +
	"\rcurrency_pair\x18\x06 \x01(\tR\fcurrencyPair\x12\x1a\n" +
	"\bquantity\x18\a \x01(\tR\bquantity\x12\x1d\n" +
	"\n" +
	"limit_rate\x18\b \x01(\tR\tlimitRate\x12\x15\n" +
	"\x06ref_id\x18\t \x01(\tR\x05refId\x12\x1b\n" +
	"\torder_day\x18\n" +
	" \x01(\tR\borderDay\x12,\n" +
	"\x12min_trade_quantity\x18\v \x01(\tR\x10minTradeQuantity\"^\n" +
	"\x13SubmitOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\"i\n" +
	"\x12CancelOrderRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x1b\n" +
	"\torder_day\x18\x03 \x01(\tR\borderDay\"\xae\x01\n" +
	"\x13CancelOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\x12remaining_quantity\x18\x02 \x01(\tR\x11remainingQuantity\x12!\n" +
	"\forder_status\x18\x03 \x01(\x05R\vorderStatus\x12\x14\n" +
	"\x05cause\x18\x04 \x01(\tR\x05cause\x12\x15\n" +
	"\x06ref_id\x18\x05 \x01(\tR\x05refId\"\x9a\x02\n" +
	"\x19FilterClientOrdersRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x12\n" +
	"\x04side\x18\x02 \x01(\x05R\x04side\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\x12#\n" +
	"\rcurrency_pair\x18\a \x01(\tR\fcurrencyPair\x12$\n" +
	"\x0eorder_day_from\x18\b \x01(\tR\forderDayFrom\x12 \n" +
	"\forder_day_to\x18\t \x01(\tR\n" +
	"orderDayTo\"I\n" +
	"\x1aFilterClientOrdersResponse\x12+\n" +
	"\x06orders\x18\x01 \x03(\v2\x13.forex.v1.OrderInfoR\x06orders\"\xaa\x03\n" +
	"\tOrderInfo\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x12\n" +
	"\x04side\x18\x02 \x01(\x05R\x04side\x12\x18\n" +
	"\asegment\x18\x03 \x01(\x05R\asegment\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12,\n" +
	"\x12allow_partial_fill\x18\x05 \x01(\bR\x10allowPartialFill\x12#\n" +
	"\rcurrency_pair\x18\x06 \x01(\tR\fcurrencyPair\x12\x1a\n" +
	"\bquantity\x18\a \x01(\tR\bquantity\x12\x1d\n" +
	"\n" +
	"limit_rate\x18\b \x01(\tR\tlimitRate\x12\x15\n" +
	"\x06ref_id\x18\t \x01(\tR\x05refId\x12,\n" +
	"\x12min_trade_quantity\x18\n" +
	" \x01(\tR\x10minTradeQuantity\x12-\n" +
	"\x12remaining_quantity\x18\v \x01(\tR\x11remainingQuantity\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\torder_day\x18\r \x01(\tR\borderDay\"\x95\x01\n" +
	"\x18GetOrderBookDepthRequest\x12\x18\n" +
	"\asegment\x18\x01 \x01(\x05R\asegment\x12\x1d\n" +
	"\n" +
	"max_levels\x18\x02 \x01(\x05R\tmaxLevels\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12#\n" +
	"\rcurrency_pair\x18\x04 \x01(\tR\fcurrencyPair\"o\n" +
	"\x19GetOrderBookDepthResponse\x12(\n" +
	"\x04bids\x18\x01 \x03(\v2\x14.forex.v1.PriceLevelR\x04bids\x12(\n" +
	"\x04asks\x18\x02 \x03(\v2\x14.forex.v1.PriceLevelR\x04asks\"G\n" +
	"\n" +
	"PriceLevel\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\tR\x04rate\x12%\n" +
	"\x0etotal_quantity\x18\x02 \x01(\tR\rtotalQuantity\"\x1d\n" +
	"\x1bSubscribeOrderEventsRequest\"\xe4\x01\n" +
	"\x1cSubscribeOrderEventsResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x05R\teventType\x12'\n" +
	"\x0fevent_timestamp\x18\x03 \x01(\tR\x0eeventTimestamp\x12-\n" +
	"\x12remaining_quantity\x18\x04 \x01(\tR\x11remainingQuantity\x12\x15\n" +
	"\x06ref_id\x18\x05 \x01(\tR\x05refId\x12\x1b\n" +
	"\torder_day\x18\x06 \x01(\tR\borderDay2\xce\x03\n" +
	"\fOrderService\x12J\n" +
	"\vSubmitOrder\x12\x1c.forex.v1.SubmitOrderRequest\x1a\x1d.forex.v1.SubmitOrderResponse\x12J\n" +
	"\vCancelOrder\x12\x1c.forex.v1.CancelOrderRequest\x1a\x1d.forex.v1.CancelOrderResponse\x12\\\n" +
	"\x11GetOrderBookDepth\x12\".forex.v1.GetOrderBookDepthRequest\x1a#.forex.v1.GetOrderBookDepthResponse\x12_\n" +
	"\x12FilterClientOrders\x12#.forex.v1.FilterClientOrdersRequest\x1a$.forex.v1.FilterClientOrdersResponse\x12g\n" +
	"\x14SubscribeOrderEvents\x12%.forex.v1.SubscribeOrderEventsRequest\x1a&.forex.v1.SubscribeOrderEventsResponse0\x01B\x8d\x01\n" +
	"\fcom.forex.v1B\n" +
	"OrderProtoP\x01Z0github.com/alifcapital/fx/proto/forex/v1;forexv1\xa2\x02\x03FXX\xaa\x02\bForex.V1\xca\x02\bForex\\V1\xe2\x02\x14Forex\\V1\\GPBMetadata\xea\x02\tForex::V1b\beditionsp\xe8\a"

var (
	file_forex_v1_order_proto_rawDescOnce sync.Once
	file_forex_v1_order_proto_rawDescData []byte
)

func file_forex_v1_order_proto_rawDescGZIP() []byte {
	file_forex_v1_order_proto_rawDescOnce.Do(func() {
		file_forex_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forex_v1_order_proto_rawDesc), len(file_forex_v1_order_proto_rawDesc)))
	})
	return file_forex_v1_order_proto_rawDescData
}

var file_forex_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_forex_v1_order_proto_goTypes = []any{
	(*SubmitOrderRequest)(nil),           // 0: forex.v1.SubmitOrderRequest
	(*SubmitOrderResponse)(nil),          // 1: forex.v1.SubmitOrderResponse
	(*CancelOrderRequest)(nil),           // 2: forex.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),          // 3: forex.v1.CancelOrderResponse
	(*FilterClientOrdersRequest)(nil),    // 4: forex.v1.FilterClientOrdersRequest
	(*FilterClientOrdersResponse)(nil),   // 5: forex.v1.FilterClientOrdersResponse
	(*OrderInfo)(nil),                    // 6: forex.v1.OrderInfo
	(*GetOrderBookDepthRequest)(nil),     // 7: forex.v1.GetOrderBookDepthRequest
	(*GetOrderBookDepthResponse)(nil),    // 8: forex.v1.GetOrderBookDepthResponse
	(*PriceLevel)(nil),                   // 9: forex.v1.PriceLevel
	(*SubscribeOrderEventsRequest)(nil),  // 10: forex.v1.SubscribeOrderEventsRequest
	(*SubscribeOrderEventsResponse)(nil), // 11: forex.v1.SubscribeOrderEventsResponse
}
var file_forex_v1_order_proto_depIdxs = []int32{
	6,  // 0: forex.v1.FilterClientOrdersResponse.orders:type_name -> forex.v1.OrderInfo
	9,  // 1: forex.v1.GetOrderBookDepthResponse.bids:type_name -> forex.v1.PriceLevel
	9,  // 2: forex.v1.GetOrderBookDepthResponse.asks:type_name -> forex.v1.PriceLevel
	0,  // 3: forex.v1.OrderService.SubmitOrder:input_type -> forex.v1.SubmitOrderRequest
	2,  // 4: forex.v1.OrderService.CancelOrder:input_type -> forex.v1.CancelOrderRequest
	7,  // 5: forex.v1.OrderService.GetOrderBookDepth:input_type -> forex.v1.GetOrderBookDepthRequest
	4,  // 6: forex.v1.OrderService.FilterClientOrders:input_type -> forex.v1.FilterClientOrdersRequest
	10, // 7: forex.v1.OrderService.SubscribeOrderEvents:input_type -> forex.v1.SubscribeOrderEventsRequest
	1,  // 8: forex.v1.OrderService.SubmitOrder:output_type -> forex.v1.SubmitOrderResponse
	3,  // 9: forex.v1.OrderService.CancelOrder:output_type -> forex.v1.CancelOrderResponse
	8,  // 10: forex.v1.OrderService.GetOrderBookDepth:output_type -> forex.v1.GetOrderBookDepthResponse
	5,  // 11: forex.v1.OrderService.FilterClientOrders:output_type -> forex.v1.FilterClientOrdersResponse
	11, // 12: forex.v1.OrderService.SubscribeOrderEvents:output_type -> forex.v1.SubscribeOrderEventsResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_forex_v1_order_proto_init() }
func file_forex_v1_order_proto_init() {
	if File_forex_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forex_v1_order_proto_rawDesc), len(file_forex_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forex_v1_order_proto_goTypes,
		DependencyIndexes: file_forex_v1_order_proto_depIdxs,
		MessageInfos:      file_forex_v1_order_proto_msgTypes,
	}.Build()
	File_forex_v1_order_proto = out.File
	file_forex_v1_order_proto_goTypes = nil
	file_forex_v1_order_proto_depIdxs = nil
}
