// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: forex/v1/partner.proto

package forexv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrencyPairsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrencyPairsRequest) Reset() {
	*x = GetCurrencyPairsRequest{}
	mi := &file_forex_v1_partner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyPairsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyPairsRequest) ProtoMessage() {}

func (x *GetCurrencyPairsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_partner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyPairsRequest.ProtoReflect.Descriptor instead.
func (*GetCurrencyPairsRequest) Descriptor() ([]byte, []int) {
	return file_forex_v1_partner_proto_rawDescGZIP(), []int{0}
}

type GetCurrencyPairsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyPairs []*CurrencyPair        `protobuf:"bytes,1,rep,name=currency_pairs,json=currencyPairs" json:"currency_pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrencyPairsResponse) Reset() {
	*x = GetCurrencyPairsResponse{}
	mi := &file_forex_v1_partner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyPairsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyPairsResponse) ProtoMessage() {}

func (x *GetCurrencyPairsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_partner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyPairsResponse.ProtoReflect.Descriptor instead.
func (*GetCurrencyPairsResponse) Descriptor() ([]byte, []int) {
	return file_forex_v1_partner_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrencyPairsResponse) GetCurrencyPairs() []*CurrencyPair {
	if x != nil {
		return x.CurrencyPairs
	}
	return nil
}

type CurrencyPair struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Pair             *string                `protobuf:"bytes,1,opt,name=pair" json:"pair,omitempty"` // "USD/TJS"
	MinLot           *string                `protobuf:"bytes,2,opt,name=min_lot,json=minLot" json:"min_lot,omitempty"`
	MinTradeQuantity *string                `protobuf:"bytes,3,opt,name=min_trade_quantity,json=minTradeQuantity" json:"min_trade_quantity,omitempty"`
	ValidRatePercent *int32                 `protobuf:"varint,4,opt,name=valid_rate_percent,json=validRatePercent" json:"valid_rate_percent,omitempty"` // % of the rate that is considered valid
	NbtAvgRate       *string                `protobuf:"bytes,5,opt,name=nbt_avg_rate,json=nbtAvgRate" json:"nbt_avg_rate,omitempty"`                    // NBT avg rate
	IsActive         *bool                  `protobuf:"varint,6,opt,name=is_active,json=isActive" json:"is_active,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CurrencyPair) Reset() {
	*x = CurrencyPair{}
	mi := &file_forex_v1_partner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyPair) ProtoMessage() {}

func (x *CurrencyPair) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_partner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyPair.ProtoReflect.Descriptor instead.
func (*CurrencyPair) Descriptor() ([]byte, []int) {
	return file_forex_v1_partner_proto_rawDescGZIP(), []int{2}
}

func (x *CurrencyPair) GetPair() string {
	if x != nil && x.Pair != nil {
		return *x.Pair
	}
	return ""
}

func (x *CurrencyPair) GetMinLot() string {
	if x != nil && x.MinLot != nil {
		return *x.MinLot
	}
	return ""
}

func (x *CurrencyPair) GetMinTradeQuantity() string {
	if x != nil && x.MinTradeQuantity != nil {
		return *x.MinTradeQuantity
	}
	return ""
}

func (x *CurrencyPair) GetValidRatePercent() int32 {
	if x != nil && x.ValidRatePercent != nil {
		return *x.ValidRatePercent
	}
	return 0
}

func (x *CurrencyPair) GetNbtAvgRate() string {
	if x != nil && x.NbtAvgRate != nil {
		return *x.NbtAvgRate
	}
	return ""
}

func (x *CurrencyPair) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

var File_forex_v1_partner_proto protoreflect.FileDescriptor

const file_forex_v1_partner_proto_rawDesc = "" +
	"\n" +
	"\x16forex/v1/partner.proto\x12\bforex.v1\"\x19\n" +
	"\x17GetCurrencyPairsRequest\"Y\n" +
	"\x18GetCurrencyPairsResponse\x12=\n" +
	"\x0ecurrency_pairs\x18\x01 \x03(\v2\x16.forex.v1.CurrencyPairR\rcurrencyPairs\"\xd6\x01\n" +
	"\fCurrencyPair\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x17\n" +
	"\amin_lot\x18\x02 \x01(\tR\x06minLot\x12,\n" +
	"\x12min_trade_quantity\x18\x03 \x01(\tR\x10minTradeQuantity\x12,\n" +
	"\x12valid_rate_percent\x18\x04 \x01(\x05R\x10validRatePercent\x12 \n" +
	"\fnbt_avg_rate\x18\x05 \x01(\tR\n" +
	"nbtAvgRate\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive2k\n" +
	"\x0ePartnerService\x12Y\n" +
	"\x10GetCurrencyPairs\x12!.forex.v1.GetCurrencyPairsRequest\x1a\".forex.v1.GetCurrencyPairsResponseB\x8f\x01\n" +
	"\fcom.forex.v1B\fPartnerProtoP\x01Z0github.com/alifcapital/fx/proto/forex/v1;forexv1\xa2\x02\x03FXX\xaa\x02\bForex.V1\xca\x02\bForex\\V1\xe2\x02\x14Forex\\V1\\GPBMetadata\xea\x02\tForex::V1b\beditionsp\xe8\a"

var (
	file_forex_v1_partner_proto_rawDescOnce sync.Once
	file_forex_v1_partner_proto_rawDescData []byte
)

func file_forex_v1_partner_proto_rawDescGZIP() []byte {
	file_forex_v1_partner_proto_rawDescOnce.Do(func() {
		file_forex_v1_partner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forex_v1_partner_proto_rawDesc), len(file_forex_v1_partner_proto_rawDesc)))
	})
	return file_forex_v1_partner_proto_rawDescData
}

var file_forex_v1_partner_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_forex_v1_partner_proto_goTypes = []any{
	(*GetCurrencyPairsRequest)(nil),  // 0: forex.v1.GetCurrencyPairsRequest
	(*GetCurrencyPairsResponse)(nil), // 1: forex.v1.GetCurrencyPairsResponse
	(*CurrencyPair)(nil),             // 2: forex.v1.CurrencyPair
}
var file_forex_v1_partner_proto_depIdxs = []int32{
	2, // 0: forex.v1.GetCurrencyPairsResponse.currency_pairs:type_name -> forex.v1.CurrencyPair
	0, // 1: forex.v1.PartnerService.GetCurrencyPairs:input_type -> forex.v1.GetCurrencyPairsRequest
	1, // 2: forex.v1.PartnerService.GetCurrencyPairs:output_type -> forex.v1.GetCurrencyPairsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_forex_v1_partner_proto_init() }
func file_forex_v1_partner_proto_init() {
	if File_forex_v1_partner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forex_v1_partner_proto_rawDesc), len(file_forex_v1_partner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forex_v1_partner_proto_goTypes,
		DependencyIndexes: file_forex_v1_partner_proto_depIdxs,
		MessageInfos:      file_forex_v1_partner_proto_msgTypes,
	}.Build()
	File_forex_v1_partner_proto = out.File
	file_forex_v1_partner_proto_goTypes = nil
	file_forex_v1_partner_proto_depIdxs = nil
}
