// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: forex/v1/trade.proto

package forexv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             *int64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	RefId          *int64                 `protobuf:"varint,2,opt,name=ref_id,json=refId" json:"ref_id,omitempty"`
	OrderId        *int64                 `protobuf:"varint,3,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	OrderStatus    *int32                 `protobuf:"varint,4,opt,name=order_status,json=orderStatus" json:"order_status,omitempty"`
	Side           *int32                 `protobuf:"varint,5,opt,name=side" json:"side,omitempty"`
	OrderDay       *string                `protobuf:"bytes,6,opt,name=order_day,json=orderDay" json:"order_day,omitempty"`
	TradingDay     *string                `protobuf:"bytes,7,opt,name=trading_day,json=tradingDay" json:"trading_day,omitempty"`
	FilledQuantity *string                `protobuf:"bytes,8,opt,name=filled_quantity,json=filledQuantity" json:"filled_quantity,omitempty"`
	ExecutionRate  *string                `protobuf:"bytes,9,opt,name=execution_rate,json=executionRate" json:"execution_rate,omitempty"`
	ExecutedAt     *string                `protobuf:"bytes,10,opt,name=executed_at,json=executedAt" json:"executed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TradeResponse) Reset() {
	*x = TradeResponse{}
	mi := &file_forex_v1_trade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeResponse) ProtoMessage() {}

func (x *TradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_trade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeResponse.ProtoReflect.Descriptor instead.
func (*TradeResponse) Descriptor() ([]byte, []int) {
	return file_forex_v1_trade_proto_rawDescGZIP(), []int{0}
}

func (x *TradeResponse) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *TradeResponse) GetRefId() int64 {
	if x != nil && x.RefId != nil {
		return *x.RefId
	}
	return 0
}

func (x *TradeResponse) GetOrderId() int64 {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return 0
}

func (x *TradeResponse) GetOrderStatus() int32 {
	if x != nil && x.OrderStatus != nil {
		return *x.OrderStatus
	}
	return 0
}

func (x *TradeResponse) GetSide() int32 {
	if x != nil && x.Side != nil {
		return *x.Side
	}
	return 0
}

func (x *TradeResponse) GetOrderDay() string {
	if x != nil && x.OrderDay != nil {
		return *x.OrderDay
	}
	return ""
}

func (x *TradeResponse) GetTradingDay() string {
	if x != nil && x.TradingDay != nil {
		return *x.TradingDay
	}
	return ""
}

func (x *TradeResponse) GetFilledQuantity() string {
	if x != nil && x.FilledQuantity != nil {
		return *x.FilledQuantity
	}
	return ""
}

func (x *TradeResponse) GetExecutionRate() string {
	if x != nil && x.ExecutionRate != nil {
		return *x.ExecutionRate
	}
	return ""
}

func (x *TradeResponse) GetExecutedAt() string {
	if x != nil && x.ExecutedAt != nil {
		return *x.ExecutedAt
	}
	return ""
}

type TradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Side          *int32                 `protobuf:"varint,1,opt,name=side" json:"side,omitempty"`
	TradeId       *int64                 `protobuf:"varint,2,opt,name=trade_id,json=tradeId" json:"trade_id,omitempty"`
	TradingDay    *string                `protobuf:"bytes,3,opt,name=trading_day,json=tradingDay" json:"trading_day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeRequest) Reset() {
	*x = TradeRequest{}
	mi := &file_forex_v1_trade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeRequest) ProtoMessage() {}

func (x *TradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forex_v1_trade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeRequest.ProtoReflect.Descriptor instead.
func (*TradeRequest) Descriptor() ([]byte, []int) {
	return file_forex_v1_trade_proto_rawDescGZIP(), []int{1}
}

func (x *TradeRequest) GetSide() int32 {
	if x != nil && x.Side != nil {
		return *x.Side
	}
	return 0
}

func (x *TradeRequest) GetTradeId() int64 {
	if x != nil && x.TradeId != nil {
		return *x.TradeId
	}
	return 0
}

func (x *TradeRequest) GetTradingDay() string {
	if x != nil && x.TradingDay != nil {
		return *x.TradingDay
	}
	return ""
}

var File_forex_v1_trade_proto protoreflect.FileDescriptor

const file_forex_v1_trade_proto_rawDesc = "" +
	"\n" +
	"\x14forex/v1/trade.proto\x12\bforex.v1\"\xb7\x02\n" +
	"\rTradeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06ref_id\x18\x02 \x01(\x03R\x05refId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x12!\n" +
	"\forder_status\x18\x04 \x01(\x05R\vorderStatus\x12\x12\n" +
	"\x04side\x18\x05 \x01(\x05R\x04side\x12\x1b\n" +
	"\torder_day\x18\x06 \x01(\tR\borderDay\x12\x1f\n" +
	"\vtrading_day\x18\a \x01(\tR\n" +
	"tradingDay\x12'\n" +
	"\x0ffilled_quantity\x18\b \x01(\tR\x0efilledQuantity\x12%\n" +
	"\x0eexecution_rate\x18\t \x01(\tR\rexecutionRate\x12\x1f\n" +
	"\vexecuted_at\x18\n" +
	" \x01(\tR\n" +
	"executedAt\"^\n" +
	"\fTradeRequest\x12\x12\n" +
	"\x04side\x18\x01 \x01(\x05R\x04side\x12\x19\n" +
	"\btrade_id\x18\x02 \x01(\x03R\atradeId\x12\x1f\n" +
	"\vtrading_day\x18\x03 \x01(\tR\n" +
	"tradingDay2L\n" +
	"\fTradeService\x12<\n" +
	"\x05Trade\x12\x16.forex.v1.TradeRequest\x1a\x17.forex.v1.TradeResponse(\x010\x01B\x8d\x01\n" +
	"\fcom.forex.v1B\n" +
	"TradeProtoP\x01Z0github.com/alifcapital/fx/proto/forex/v1;forexv1\xa2\x02\x03FXX\xaa\x02\bForex.V1\xca\x02\bForex\\V1\xe2\x02\x14Forex\\V1\\GPBMetadata\xea\x02\tForex::V1b\beditionsp\xe8\a"

var (
	file_forex_v1_trade_proto_rawDescOnce sync.Once
	file_forex_v1_trade_proto_rawDescData []byte
)

func file_forex_v1_trade_proto_rawDescGZIP() []byte {
	file_forex_v1_trade_proto_rawDescOnce.Do(func() {
		file_forex_v1_trade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forex_v1_trade_proto_rawDesc), len(file_forex_v1_trade_proto_rawDesc)))
	})
	return file_forex_v1_trade_proto_rawDescData
}

var file_forex_v1_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_forex_v1_trade_proto_goTypes = []any{
	(*TradeResponse)(nil), // 0: forex.v1.TradeResponse
	(*TradeRequest)(nil),  // 1: forex.v1.TradeRequest
}
var file_forex_v1_trade_proto_depIdxs = []int32{
	1, // 0: forex.v1.TradeService.Trade:input_type -> forex.v1.TradeRequest
	0, // 1: forex.v1.TradeService.Trade:output_type -> forex.v1.TradeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_forex_v1_trade_proto_init() }
func file_forex_v1_trade_proto_init() {
	if File_forex_v1_trade_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forex_v1_trade_proto_rawDesc), len(file_forex_v1_trade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forex_v1_trade_proto_goTypes,
		DependencyIndexes: file_forex_v1_trade_proto_depIdxs,
		MessageInfos:      file_forex_v1_trade_proto_msgTypes,
	}.Build()
	File_forex_v1_trade_proto = out.File
	file_forex_v1_trade_proto_goTypes = nil
	file_forex_v1_trade_proto_depIdxs = nil
}
