// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: forex/v1/trade.proto

package forexv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TradeService_Trade_FullMethodName          = "/forex.v1.TradeService/Trade"
	TradeService_Reconciliation_FullMethodName = "/forex.v1.TradeService/Reconciliation"
	TradeService_GetTrades_FullMethodName      = "/forex.v1.TradeService/GetTrades"
)

// TradeServiceClient is the client API for TradeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeServiceClient interface {
	Trade(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TradeRequest, TradeResponse], error)
	Reconciliation(ctx context.Context, in *ReconciliationRequest, opts ...grpc.CallOption) (*ReconciliationResponse, error)
	GetTrades(ctx context.Context, in *GetTradesRequest, opts ...grpc.CallOption) (*GetTradesResponse, error)
}

type tradeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeServiceClient(cc grpc.ClientConnInterface) TradeServiceClient {
	return &tradeServiceClient{cc}
}

func (c *tradeServiceClient) Trade(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TradeRequest, TradeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TradeService_ServiceDesc.Streams[0], TradeService_Trade_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TradeRequest, TradeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TradeService_TradeClient = grpc.BidiStreamingClient[TradeRequest, TradeResponse]

func (c *tradeServiceClient) Reconciliation(ctx context.Context, in *ReconciliationRequest, opts ...grpc.CallOption) (*ReconciliationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconciliationResponse)
	err := c.cc.Invoke(ctx, TradeService_Reconciliation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeServiceClient) GetTrades(ctx context.Context, in *GetTradesRequest, opts ...grpc.CallOption) (*GetTradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTradesResponse)
	err := c.cc.Invoke(ctx, TradeService_GetTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeServiceServer is the server API for TradeService service.
// All implementations must embed UnimplementedTradeServiceServer
// for forward compatibility.
type TradeServiceServer interface {
	Trade(grpc.BidiStreamingServer[TradeRequest, TradeResponse]) error
	Reconciliation(context.Context, *ReconciliationRequest) (*ReconciliationResponse, error)
	GetTrades(context.Context, *GetTradesRequest) (*GetTradesResponse, error)
	mustEmbedUnimplementedTradeServiceServer()
}

// UnimplementedTradeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradeServiceServer struct{}

func (UnimplementedTradeServiceServer) Trade(grpc.BidiStreamingServer[TradeRequest, TradeResponse]) error {
	return status.Error(codes.Unimplemented, "method Trade not implemented")
}
func (UnimplementedTradeServiceServer) Reconciliation(context.Context, *ReconciliationRequest) (*ReconciliationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reconciliation not implemented")
}
func (UnimplementedTradeServiceServer) GetTrades(context.Context, *GetTradesRequest) (*GetTradesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrades not implemented")
}
func (UnimplementedTradeServiceServer) mustEmbedUnimplementedTradeServiceServer() {}
func (UnimplementedTradeServiceServer) testEmbeddedByValue()                      {}

// UnsafeTradeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeServiceServer will
// result in compilation errors.
type UnsafeTradeServiceServer interface {
	mustEmbedUnimplementedTradeServiceServer()
}

func RegisterTradeServiceServer(s grpc.ServiceRegistrar, srv TradeServiceServer) {
	// If the following call panics, it indicates UnimplementedTradeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TradeService_ServiceDesc, srv)
}

func _TradeService_Trade_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TradeServiceServer).Trade(&grpc.GenericServerStream[TradeRequest, TradeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TradeService_TradeServer = grpc.BidiStreamingServer[TradeRequest, TradeResponse]

func _TradeService_Reconciliation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconciliationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServiceServer).Reconciliation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeService_Reconciliation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServiceServer).Reconciliation(ctx, req.(*ReconciliationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeService_GetTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeServiceServer).GetTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeService_GetTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeServiceServer).GetTrades(ctx, req.(*GetTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TradeService_ServiceDesc is the grpc.ServiceDesc for TradeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forex.v1.TradeService",
	HandlerType: (*TradeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reconciliation",
			Handler:    _TradeService_Reconciliation_Handler,
		},
		{
			MethodName: "GetTrades",
			Handler:    _TradeService_GetTrades_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Trade",
			Handler:       _TradeService_Trade_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "forex/v1/trade.proto",
}
